name: Periodic GET Request

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  send-get-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET request
        run: curl -X GET https://discordlinkfix.onrender.com/
